#!/bin/bash
echo "🧪 Testing Debug UI..."
echo ""
echo "1. Checking if file updated on server:"
curl -s http://localhost:8000/src/modules/debug/index.html | grep "v2 FIXED" && echo "   ✅ Server has v2 FIXED" || echo "   ❌ Server still old"
echo ""
echo "2. Checking import path:"
curl -s http://localhost:8000/src/modules/debug/index.html | grep "import.*WORKER_CONFIG.*from.*'../../config" && echo "   ✅ Import path correct" || echo "   ❌ Import path wrong"
echo ""
echo "3. Checking module tabs:"
curl -s http://localhost:8000/src/modules/debug/index.html | grep "module-catalog" && echo "   ✅ Catalog module exists" || echo "   ❌ No catalog module"
echo ""
echo "4. Checking View Cache button:"
curl -s http://localhost:8000/src/modules/debug/index.html | grep "viewCachedProducts" && echo "   ✅ View Cache button exists" || echo "   ❌ No View Cache button"
echo ""
echo "📋 Now in browser:"
echo "   1. Open: http://localhost:8000/debug.html"
echo "   2. Do: Ctrl+Shift+R (hard refresh)"
echo "   3. Check title shows: '🔍 Serpent Town Debug v2 FIXED'"
echo "   4. If not updated, clear cache in browser settings"
